# Generated by Django 4.2 on 2023-06-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costumer',
            options={'ordering': ['-name'], 'verbose_name': 'Zakaznik', 'verbose_name_plural': 'Zakaznici'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['-name'], 'verbose_name': 'Vyvojar', 'verbose_name_plural': 'Vyvojari'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-name'], 'verbose_name': 'Hra', 'verbose_name_plural': 'Hry'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['-name'], 'verbose_name': 'Zanr', 'verbose_name_plural': 'Zanry'},
        ),
        migrations.AddField(
            model_name='developer',
            name='games',
            field=models.ManyToManyField(to='gameapp.game'),
        ),
    ]
