# Generated by Django 4.2 on 2023-06-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_alter_costumer_options_alter_developer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='icon',
            field=models.ImageField(blank=True, help_text='Nahrejte fotku', null=True, upload_to='', verbose_name='Icona Dev'),
        ),
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, help_text='Nahrejte fotku¨¨', null=True, upload_to='', verbose_name='Obrazek hry'),
        ),
    ]
