# Generated by Django 4.2 on 2023-06-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_developer_icon_game_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='games',
            field=models.ManyToManyField(null=True, to='gameapp.game'),
        ),
    ]
