# Generated by Django 4.2 on 2023-06-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0004_alter_developer_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datum',
            field=models.DateField(blank=True, null=True, verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload a game icon', null=True, upload_to='', verbose_name='Game icon'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(help_text='Enter the name of the game', max_length=50, unique=True, verbose_name='Game name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='popis',
            field=models.TextField(blank=True, help_text='Enter a description of the game', null=True),
        ),
    ]
