# Generated by Django 4.2 on 2023-06-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0006_remove_game_zanr_remove_game_hodnoceni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='zanr',
            field=models.ManyToManyField(to='gameapp.genres'),
        ),
        migrations.AlterField(
            model_name='game',
            name='datum',
            field=models.DateField(blank=True, null=True, verbose_name='datum vydání'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='hodnoceni',
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, help_text='Nahrejte fotku¨¨', null=True, upload_to='', verbose_name='Obrazek hry'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(help_text='Enter a name of Game', max_length=50, unique=True, verbose_name='Game name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='popis',
            field=models.TextField(blank=True, help_text='Enter description of the game', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='hodnoceni',
            field=models.ManyToManyField(to='gameapp.hodnoceni'),
        ),
    ]
